-- Créer la base et les schémas
CREATE DATABASE IF NOT EXISTS HOPITAL_DW;

USE DATABASE HOPITAL_DW;

CREATE SCHEMA IF NOT EXISTS STG;
CREATE SCHEMA IF NOT EXISTS OBS;
CREATE SCHEMA IF NOT EXISTS WRK;
CREATE SCHEMA IF NOT EXISTS REJ;
CREATE SCHEMA IF NOT EXISTS SOC;
CREATE SCHEMA IF NOT EXISTS TCH;
CREATE SCHEMA IF NOT EXISTS VW;

-- Créer warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 10
    AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 5
    AUTO_RESUME = TRUE;
